from django.urls import path

from apps.cms import admin_views as cms_views

from . import views

urlpatterns = [
    path("admin/overview/", views.overview),
    path("admin/sections/", cms_views.sections),
    path("admin/sections/reorder/", cms_views.reorder_sections),
    path("admin/sections/<str:pk>/", cms_views.section_detail),
    path("admin/articles/", cms_views.articles),
    path("admin/articles/<str:pk>/", cms_views.article_detail),
    path("admin/categories/", views.categories),
    path("admin/categories/<str:pk>/", views.category_detail),
    path("admin/instructors/", views.instructors),
    path("admin/courses/", views.courses),
    path("admin/courses/<str:pk>/", views.course_detail_view),
    path("admin/courses/<str:pk>/parts/", views.course_parts),
    path("admin/parts/reorder/", views.reorder_parts),
    path("admin/parts/<str:pk>/", views.part_detail),
    path("admin/parts/<str:pk>/videos/", views.part_videos),
    path("admin/videos/reorder/", views.reorder_videos),
    path("admin/videos/<str:pk>/", views.video_detail),
    path("admin/upload/video/", views.upload_video),
    path("admin/upload/image/", views.upload_image),
    path("admin/upload/audio/", views.upload_audio),
    path("admin/podcasts/", views.podcasts),
    path("admin/podcasts/<str:pk>/", views.podcast_detail),
    path("admin/podcasts/<str:pk>/episodes/", views.podcast_episodes),
    path("admin/episodes/<str:pk>/", views.episode_detail),
    path("admin/exams/<str:pk>/codes/", views.exam_codes),
    path("admin/codes/<str:pk>/", views.exam_code_detail),
    path("admin/codes/<str:pk>/modules/", views.exam_code_modules),
    path("admin/codes/<str:pk>/modules/<int:index>/", views.exam_code_module_detail),
    path("admin/codes/<str:pk>/modules/<int:index>/parts/", views.exam_code_parts),
    path("admin/codes/<str:pk>/modules/<int:index>/parts/<int:part_index>/", views.exam_code_part_detail),
    path("admin/codes/<str:pk>/modules/<int:index>/parts/<int:part_index>/items/", views.exam_code_items),
    path("admin/plans/", views.plans),
    path("admin/plans/<str:pk>/", views.plan_detail),
    path("admin/exams/", views.exams),
    path("admin/exams/<str:pk>/", views.exam_detail_view),
    path("admin/exams/<str:pk>/modules/", views.exam_modules),
    path("admin/exams/<str:pk>/modules/<int:index>/", views.exam_module_detail),
    path("admin/exams/<str:pk>/modules/<int:index>/parts/", views.exam_parts),
    path("admin/exams/<str:pk>/modules/<int:index>/parts/<int:part_index>/", views.exam_part_detail),
    path("admin/exams/<str:pk>/modules/<int:index>/parts/<int:part_index>/items/", views.exam_items),
]
